# Generated by Django 5.1.1 on 2024-09-15 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_task_register_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalized_date', models.DateTimeField()),
                ('hours_worked', models.FloatField()),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.worker')),
            ],
        ),
    ]
