# Generated by Django 5.1.1 on 2024-09-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_realtimework'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimework',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
